# Calibration of baseline and scenario shocks script : objective is to create the calibration databases for the baseline and for each shock. 

## A. Loading calib.csv generated by dynamo 

calib <- fread("src/compiler/calib.csv", data.table = FALSE) %>% 
  select(-all_of("baseyear")) %>% 
  mutate(year = year + baseyear) 

OGcalib <- calib

## B Baseline shock calibration (ie deviating from the steady state at the baseline configuration)
source(calib_baseline)
write.csv(baseline_ch, 
          file = file.path("configuration","scenarii_calib","calib_baseline.csv"),
          row.names = FALSE)

## C Modified calib to integrate potential baseline changes

baseline_vars <- setdiff(names(baseline_ch), "year")

calib_new_base <- OGcalib %>% 
  filter(year %in% c(firstyear:lastyear)) %>% 
  select(-all_of(baseline_vars)) %>% 
  full_join(baseline_ch, by= "year")
  ### calib_new_base now integrates changes with the baseline scenario and should be used to configure shock scenarii

## D Scenarii shock calibration
if(automated_shocks == FALSE){
  shock_ch_scenarii <- scenario %>% 
    map(~source(file.path("configuration","scenarii_calib", str_c("2_calib_shock_",.x,".R")))) %>% 
    map(~.x$value) %>% 
    set_names(scenario)
}else{
  source(calib_scenario)
  shock_ch_scenarii <- scenario %>% 
    map( ~automated_calib_shock(.x,calib_new_base, parameters_range) )%>%
    set_names(scenario)
}

if(Rsolver== FALSE){
shock_ch_scenarii %>% imap(~write.csv(.x, 
                                     file = file.path("configuration","scenarii_calib",str_c("calib_shock_",.y,".csv")),
                                     row.names = FALSE))}

all_scenarii <- append(shock_ch_scenarii,  list(baseline_ch) ) %>% set_names(c(scenario, "baseline"))


## E. Saving all scenarii to an Excel spreadsheet (it is only for ex-post checking purposes)

### Save a summary of all scenarii to Excel
xlsx.file = "configuration/scenarii_calib/summary_of_scenarii.xlsx"
wb <- createWorkbook()

addWorksheet(wb, "Sheet 1")
saveWorkbook(wb, xlsx.file, overwrite = TRUE)

### Preparing the workbook
wb <- loadWorkbook(xlsx.file)

all_scenarii %>% imap(function(database, name) {
  if (!name %in% sheets(wb)){ 
    addWorksheet(wb,sheetName = name) 
  }else{
    removeWorksheet(wb,name)
    addWorksheet(wb,sheetName = name) 
  }
  
  n_cols <- ncol(database) - 1
  
  writeData(wb , t(database),    sheet = name, startCol = "B", startRow = 1, colNames = FALSE, rowNames = TRUE)
  writeData(wb , "" ,            sheet = name, startCol = "B", startRow = 1, colNames = FALSE, rowNames = FALSE)
  writeData(wb , n_cols ,        sheet = name, startCol = "A", startRow = 1, colNames = FALSE, rowNames = FALSE)
  writeData(wb , rep(1,n_cols) , sheet = name, startCol = "A", startRow = 2, colNames = FALSE, rowNames = FALSE)
  
    })

### saving 
saveWorkbook(wb,xlsx.file,overwrite = TRUE)


#### Relevant Checks
# source(file.path("src","02b_ParametersandChecks.R"))
####

rm( wb, xlsx.file)
